# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c194f0ee9437206c7aac351fd5426203137f85ca1e61c63ebd409290224e971fb64388ce4a5384a85eebfe7ab3b883dfacf1e05b0decf4ff1d0d65af43ece784

test:
  secret_key_base: ade361bcd61930509909adaf4149d469dee1bdac27f20a7364d0458f6cc6fe88ee110291641560d00edaa458aba2a2c8b1541aa787c40916cab55ac20a8e1d2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
